feat: dockge agent friendly name
louislam/dockge pull request #414
Opened 2024-02-01 07:29 UTC by lohrbini

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/dockge/blob/master/CONTRIBUTING.md

Tick the checkbox if you understand [x]: 
- [ X] I have read and understand the pull request rules.

# Disclaimer
I am not a Software programmer and only have basic understandings on any Programming Languages used in the project, so please be patient and maybe assist me with further development of this feature

# Description
Since `dockge agents` is still a beta feature and in the future maybe more and more remote instances will be added I wanted to enable the option for setting a friendly name for a remote instance. If the name is not set via the prompt. The default `agent.url` will be displayed
Fixes #(issue)

## Type of change
- New feature (non-breaking change which adds functionality)

- [ X] My code follows the style guidelines of this project
- [ X] I ran ESLint and other linters for modified files
- [ X] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ X] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots 

![dgagents-friendlyname](https://github.com/louislam/dockge/assets/10088089/6be5ff31-c4cc-4db5-b882-6abc21b79e3a)

2024-02-01 18:10 UTC, cyril59310 commented
After testing your PR, I have two small remarks:

1) Could you add the translation key "Friendly Name" to the en.json file?
2) It would be interesting for the friendly name to be applied here as well
![si7sb7](https://github.com/louislam/dockge/assets/70776486/5f7e3d2f-a3ec-4f85-a224-d82dae1ba5f4)

2024-02-01 18:49 UTC, cyril59310 commented
In the file 

> frontend/src/lang/en.json ,

please add `"Friendly Name": "Friendly Name"` so that translators can translate it into other languages using our Weblate tool.

2024-02-01 21:35 UTC, lohrbini commented
@cyril59310 bulletpoint 2 of your request is now already done. Only need to update codebase and remove all debug options

![image](https://github.com/louislam/dockge/assets/10088089/269d56db-4988-43aa-80f2-64fcd97e3da0)

2024-02-02 05:05 UTC, larswmh commented on frontend/src/mixins/socket.ts
> +                    }
Thank you so much for this pull request. Just a small suggestion to avoid [CI test failure](https://github.com/louislam/dockge/actions/runs/7748302986/job/21130673284?pr=414#step:10:94)
- Replaces single quotes with double quotes
- Remove duplicate space in Line 139
```suggestion
                    if (endpoint === v["endpoint"] && v["friendlyname"] !== "") {
                        return v["friendlyname"];
                    }
                    if (endpoint === v["endpoint"] && v["friendlyname"] === "") {
                        return endpoint;
                    }
```

2024-02-02 06:18 UTC, lohrbini commented on frontend/src/mixins/socket.ts
> +                    }
Oh sorry! Did not see your suggestions I already rebased. But thanks in advance!

2024-02-02 17:12 UTC, cyril59310 commented
Thank you for taking my feedback. 
I noticed afterwards that here too, the friendly name could be added.
![image](https://github.com/louislam/dockge/assets/70776486/d6af505c-e407-43bf-979e-b4b12c12c43c)

2024-02-03 15:04 UTC, lohrbini commented
Thanks again @cyril59310 . This is now also implemented

2024-02-06 07:03 UTC, lohrbini commented
Finally I was able to get the `update` feature working. Friendly names are now updated properly by a small dialog

2024-02-06 17:53 UTC, cyril59310 commented
J'ai fait quelques suggestions afin d'ajouter des clés de traduction pour nos traducteurs.

2024-02-06 21:59 UTC, louislam commented on backend/migrations/2023-12-20-2117-agent-table.ts
> +        table.string("friendlyname", 255);
This file cannot be modified. Have to create a new file. 

Migration guide:
https://github.com/louislam/uptime-kuma/tree/master/db/knex_migrations


Will come back later, as I would like to finish the next milestone of Uptime Kuma first.

2024-02-06 22:03 UTC, louislam commented on backend/agent-manager.ts
> +    async add(url : string, username : string, password : string, friendlyname : string) : Promise<Agent> {
Name Conventions

- Javascript/Typescript: camelCaseType
- SQLite: snake_case (Underscore)
- CSS/SCSS: kebab-case (Dash)


https://github.com/louislam/dockge/blob/master/CONTRIBUTING.md#name-conventions

2024-04-23 04:51 UTC, nathan815 reviewed
Nice feature!

Have some code feedback

2024-04-23 04:51 UTC, nathan815 commented on backend/agent-manager.ts
> +        await R.exec("UPDATE agent SET friendlyname = " + updatedFriendlyName + " WHERE friendlyname = " + friendlyname + "");
SQL injection vuln here - if name has quotes this will break.

You can use parameter bindings to build queries safely: 

```ts
await R.exec("UPDATE agent SET friendlyname = ? WHERE friendlyname = ?", [
    updatedFriendlyName,
    friendlyname
]);
```

https://github.com/louislam/redbean-node/blob/master/docs/Query.md

2024-04-23 04:51 UTC, nathan815 commented on backend/agent-manager.ts
> +    async update(friendlyname : string, updatedFriendlyName : string) {
I would consider accepting the agent's `id` or the `url` here for identifying the agent to update instead of friendly name.

ID is the primary key, so thats probably best to use for updating the agent. But URL is always set and has a unique constraint, so it will work too.

2024-04-23 04:51 UTC, nathan815 commented on backend/models/agent.ts
> +            updatedFriendlyName: this.updatedFriendlyName
Why is `updatedFriendlyName` also here on the model? Shouldn't just `friendlyName` be sufficient?

2024-04-23 04:51 UTC, nathan815 commented on backend/agent-manager.ts
> +        await R.exec("UPDATE agent SET friendlyname = " + updatedFriendlyName + " WHERE friendlyname = " + friendlyname + "");
Instead of a raw query, you could utilize the redbean ORM methods. See: https://github.com/louislam/redbean-node/blob/master/docs/Create-Update-Bean.md

Something like this if by ID (primary key):

```ts
const agent = await R.load('agent', id);
agent.friendlyName = friendlyName;
await R.store(agent);
```

Or by URL:

```ts
const agent = await R.findOne('agent', ' url = ? ', [url]);
agent.friendlyName = friendlyName;
await R.store(agent);
```

2024-05-22 19:12 UTC, lohrbini commented
Long time no see. Will have a look the next days on all your feedback. Many thanks 🙏🏻

2024-06-04 17:43 UTC, kayakyakr reviewed
I appreciate this addition. Short of hacking the docker swarm mechanics to do node auto-discovery, I think is a fairly nice quality of life improvement.

Left some comments on some changes I'd make to make this prod-ready.

2024-06-04 17:43 UTC, kayakyakr commented on backend/agent-manager.ts
> +    async update(friendlyname : string, updatedFriendlyName : string) {
I agree with nathan, I would refactor to pass id around for the agent

2024-06-04 17:43 UTC, kayakyakr commented on backend/models/agent.ts
> +            friendlyname: this.friendlyname,
recommendation: you should consider just naming this field `name`. There are no conflicts using the simpler version of the field name.

2024-06-04 17:43 UTC, kayakyakr commented on backend/socket-handlers/manage-agent-socket-handler.ts
> +                }
the more you know: since this is typescript, you shouldn't actually need to typecheck the input value for friendly name. We already know it's a string from before.

2024-06-04 17:43 UTC, kayakyakr commented on frontend/src/pages/DashboardHome.vue
> +                            <font-awesome-icon v-if="agent.friendlyname !== '' && agent.friendlyname !== ''" icon="pen-to-square" @click="showEditAgentFriendlynameDialog[agent.friendlyname] = !showEd
suggestion: I'm not sure why you're checking for blank string twice here, but if you switch to passing around `agent.id` you will be able to edit a name no matter if the server was created with friendly name or not, so the v-if will be unnecessary.

2024-06-04 17:43 UTC, kayakyakr commented on frontend/src/pages/DashboardHome.vue
> +                                <input id="updatedFriendlyName" v-model="agent.updatedFriendlyName" type="text" class="form-control" optional>
suggestion: similar to nathan's commends up above, if you are finding agents by their ID, you can just set `agent.name` here and use that to update the value. You also then don't have to show `Current value:` in the label, because the input will have the current value. You may want to show `agent.url` as part of the label, though, in case input name is blank.

2024-06-04 17:43 UTC, kayakyakr commented on frontend/src/pages/DashboardHome.vue
> +                            </template>
Couple of suggestions here: 

1. We can use the fact that an empty string is falsy to shorten this chain.
2. You probably don't want to be modifying things so drastically. If it's working, then a small change will do.

```suggestion
                            <span v-if="endpoint === ''" class="badge bg-secondary me-2">{{ $t("currentEndpoint") }}</span>
                            <a v-else :href="agent.url" target="_blank">{{ agent.name || endpoint }}</a>
```

2024-06-21 05:11 UTC, mon5termatt commented
would love for this to be added!

2024-08-06 15:51 UTC, lohrbini commented on backend/agent-manager.ts
> +    async update(friendlyname : string, updatedFriendlyName : string) {
sure it should be the `id` ? it is currently not passed in the agentList and needs to be added. If a host will be added and deleted it will still increase and not release a taken number. The `url` would be the "better" identifier ? 
( just a small comment. I am not against refactoring this to `id` but while updating this MR I was thinking about)

2024-08-06 16:05 UTC, lohrbini commented on backend/agent-manager.ts
> +    async add(url : string, username : string, password : string, friendlyname : string) : Promise<Agent> {
all namings has been updated

2024-08-06 16:06 UTC, lohrbini commented on backend/agent-manager.ts
> +        await R.exec("UPDATE agent SET friendlyname = " + updatedFriendlyName + " WHERE friendlyname = " + friendlyname + "");
Thanks for the input. Added this with `update by url` and started a small "discussion"
https://github.com/louislam/dockge/pull/414#discussion_r1705773795

2024-08-06 16:09 UTC, lohrbini commented on backend/models/agent.ts
> +            updatedFriendlyName: this.updatedFriendlyName
I forgot to update this file while adding the other suggestions but it still worked with the correct variables. Where is this needed 🤔

2024-08-06 16:11 UTC, lohrbini commented
Ready & happy about a second review :)

2024-08-14 10:51 UTC, larswmh commented on frontend/src/pages/DashboardHome.vue
> +                                <span v-else :href="agent.url">{{ agent.name }}</span>
```suggestion
                                <span v-if="endpoint === '' && agent.name === ''" class="badge bg-secondary me-2">Controller</span>
                                <span v-else-if="agent.name === ''" :href="agent.url">{{ endpoint }}</span>
                                <span v-else :href="agent.url">{{ agent.name }}</span>
```

2024-08-14 10:53 UTC, larswmh commented on backend/agent-manager.ts
> +     * @param updatedName
```suggestion
     * @param updatedName
```
Parameter updatedName is not used in this function, can be removed

2024-08-17 12:50 UTC, XenoUniv3rse commented
on which tag do i need to be to have this feature?

2024-08-17 13:06 UTC, lohrbini commented
> on which tag do i need to be to have this feature? 
> 
> 

It is planned to be included in the next release v1.5.0 . To use this feature you need to be on my branch and build the image on your own

2024-08-20 07:59 UTC, lohrbini commented on backend/agent-manager.ts
> +     * @param updatedName
Thanks for the feedback. Updated in latest commit

2024-08-20 07:59 UTC, lohrbini commented on frontend/src/pages/DashboardHome.vue
> +                                <span v-else :href="agent.url">{{ agent.name }}</span>
Thanks for the feedback. Updated in latest commit

2025-06-03 01:24 UTC, Dracrius commented
Love the addition but I noticed a few things. Firstly you can't rename the default `Controller` but it still has a rename button. 
![image](https://github.com/user-attachments/assets/f31fa425-3730-4a1b-aa09-6e552e627b13)

When pressed it will show nothing after `Current value: ` 
![image](https://github.com/user-attachments/assets/5b8bb5af-3f8a-4a64-b4e0-b7c20e11d3c5)

Entering a name results in an `Agent not found` error. 
![image](https://github.com/user-attachments/assets/f85651c0-48ab-44ce-afa4-6ea2081921a2)

Last thing I've noticed is on the page for any stack  in the `Controller` agent the brackets are empty but present `()`
![image](https://github.com/user-attachments/assets/0b7479b4-2d14-4813-87e8-ee1561ab6ac5)
![image](https://github.com/user-attachments/assets/e0d9f8a5-61fd-4ee4-8fad-f2845ee5113d)

I would personally love to rename `Controller` but if it can't or shouldn't be renamed the button should be removed and the brackets hidden.

2025-06-03 02:30 UTC, Dracrius requested changes
With these two changes we can wipe out the obvious bugs hanging around from the edits.

![image](https://github.com/user-attachments/assets/b5e4938a-ce51-494d-a182-39fc71c3c5ba)
![image](https://github.com/user-attachments/assets/8af27cf4-053a-4b84-8587-f94a8414e1e1)

I'll also say I much prefer the original name of `Current` for the current agent. I don't really understand the change to `Controller`.

2025-06-03 02:30 UTC, Dracrius commented on frontend/src/pages/DashboardHome.vue
> +                            <font-awesome-icon icon="pen-to-square" @click="showEditAgentNameDialog[agent.name] = !showEditAgentNameDialog[agent.Name]" />
This currently adds the edit button to the current/controller even though you can not give it a custom name. You use to have a check here but you removed both checks when someone mentioned you were checking twice.

```
<!-- Remove Button -->
<font-awesome-icon v-if="endpoint !== ''" class="ms-2 remove-agent" icon="trash" @click="showRemoveAgentDialog[agent.url] = !showRemoveAgentDialog[agent.url]" />
```

2025-06-03 02:30 UTC, Dracrius commented on frontend/src/pages/Compose.vue
If you edit line 7 to include an endpoint check it will prevent the empty brackets from displaying on current/controller controlled stacks.

`<span v-if="$root.agentCount > 1 && endpoint !== ''" class="agent-name">`

2026-04-11 19:46 UTC, merged