Added some new languages de/ab/ru/pl
louislam/dockge pull request #90
Opened 2023-11-20 08:54 UTC by operationairstrike

Added German language.

2023-11-20 09:05 UTC, operationairstrike commented
Added Arabic language.

2023-11-20 09:18 UTC, operationairstrike commented
Added russian

2023-11-20 11:11 UTC, operationairstrike commented
ready to merge

2023-11-20 11:51 UTC, louislam commented
Thanks, but were they translated by a tool or human?

2023-11-20 11:55 UTC, Zaid-maker commented
> Thanks, but were they translated by a tool or human?

Looks like done by a tool, because it took time to translate by Human.

2023-11-20 12:39 UTC, operationairstrike commented
Ok

2023-11-20 12:39 UTC, operationairstrike commented
> Thanks, but were they translated by a tool or human? 

By a tool but as long as it's correct that doesn't matter right?

2023-11-20 13:59 UTC, Zaid-maker commented
i think u mis-understood what he meant.

2023-11-20 14:30 UTC, operationairstrike commented
Tell me what he meant then

2023-11-20 14:31 UTC, operationairstrike commented
Tell me what he meant then

2023-11-20 14:31 UTC, operationairstrike commented
I'm actually to dumb to split it up into separate pull request.

2023-11-20 15:02 UTC, Zaid-maker commented
> 1. Please breakdown the languages into other pull requests, so native people could help to review.


> > Tell me what he meant then
> > Please breakdown the languages into other pull requests, so native people could help to review.
> He says make a new PR's for every new Language Translation you are doing, instead of creating all in one PR so the People speaking native language can review!

2023-11-20 21:24 UTC, operationairstrike commented
> > Tell me what he meant then
> 
> > Please breakdown the languages into other pull requests, so native people could help to review.
> 
> He says make a new PR's for every new Language Translation you are doing, instead of creating all in one PR so the People speaking native language can review!

Ik but the thing is it's a lot of work to delete all of it and make a new one the thing is that takes a lot of time like why can't people just use one all languages are in the title.

2023-11-20 21:28 UTC, operationairstrike commented
Why does it need multiple pull request if the translation is completed?

2023-11-21 06:27 UTC, furkanipek commented
Copy your translation files to a different directory.
After copying, paste the individual files between the language files in the dockge. After creating a new PR, repeat this process for a different language.

This will make the process easier.

2023-11-21 11:12 UTC, Zaid-maker commented
> Ik but the thing is it's a lot of work to delete all of it and make a new one the thing is that takes a lot of time like why can't people just use one all languages are in the title.

As u know we have a tool in Uptime Kuma which open a single Translation PR and people speaking native language can review on the Web, but in this project Louis said he don't have time to setup the tool right now. Maybe in future he will. But right know we are required to open one Pull Request for single language translation everyone is following that same manner and u are required aswell, Hope that's help 👍

2023-11-21 14:25 UTC, Aonodensetsu requested changes
native speaker reporting for duty :)

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "languageName": "Polish",
```suggestion
    "languageName": "Polski",
```
language names are typically in the language itself

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "restartPolicyUnlessStopped": "Chyba że zatrzymano",
```suggestion
    "restartPolicyUnlessStopped": "Jeśli nie zatrzymano",
```
"in the case that it was not stopped" seems more accurate for the language
```suggestion
    "restartPolicyUnlessStopped": "Chyba, że zatrzymano",
```
alternatively, the gramatically correct version requires a comma before "że"

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "restartPolicyNo": "Nie",
```suggestion
    "restartPolicyNo": "Nie restartuj",
```
"no" isn't very descriptive, "don't restart" is a more appropriate message - even though it's a less direct translation

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "volume": "Wolumen | Wolumeny",
```suggestion
    "volume": "Wolumin | Woluminy",
```
disputed, but the most common spelling of the word uses the vowel "i"

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "deleteContainer": "Usuń",
```suggestion
    "deleteContainer": "Usuń kontener",
```
consistency with translations below

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "disableauth.message2": "Przeznaczone dla scenariuszy <strong>gdzie zamierzasz zaimplementować uwierzytelnianie zewnętrzne</strong> przed Dockge, takie jak Cloudflare Access, Authelia lub inne me
```suggestion
    "disableauth.message2": "Przeznaczone dla sytuacji, <strong>w których zamierzasz zaimplementować zewnętrzne mechanizmy uwierzytelniania</strong> przed Dockge, takie jak Cloudflare Access, Authelia lub inne.",
```
more natural wording

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "passwordNotMatchMsg": "Powtórzone hasło nie pasuje.",
```suggestion
    "passwordNotMatchMsg": "Hasła się nie zgadzają.",
```
the original was correct, but this is the wording used in most applications, it will be more understandable

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "Frontend Version": "Wersja frontu",
```suggestion
    "Frontend Version": "Wersja interfejsu graficznego",
```
reworded frontend to GUI, which is better than "front" which is not polish
```suggestion
    "Frontend Version": "Wersja frontend",
```
alternatively, use the actual english word instead of translating partially

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "Show update if available": "Pokaż aktualizację, jeśli dostępna",
```suggestion
    "Show update if available": "Pokaż aktualizacje, jeśli dostępne",
```
plural for consistency

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "Also check beta release": "Sprawdź także wydanie beta",
```suggestion
    "Also check beta release": "Sprawdź także wersje beta",
```
version is a more suitable word for the language (+plural for consistency)

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "Docker Run": "Uruchomienie Docker",
```suggestion
    "Docker Run": "Uruchom za pomocą Dockera",
```
"run with the use of Docker" instead of "run docker (as in docker itself, not a container on it)"

2023-11-21 14:25 UTC, Aonodensetsu commented on frontend/src/lang/pl-PL.json
> +    "exited": "zakończony",
```suggestion
    "exited": "wyłączony",
```
"turned off" instead of "ended"

2023-11-21 15:42 UTC, louislam commented
@Aonodensetsu Would you mind to create a new pull request? 

This pull is going to be closed, it is really hard to be merged.

2023-11-21 15:42 UTC, closed without merging