Arabic
louislam/dockge pull request #99
Opened 2023-11-20 14:42 UTC by operationairstrike

2023-11-20 19:57 UTC, Zaid-maker reviewed
Please add a single language translation at a time with proper Title and descrition of the PR

2023-11-21 11:14 UTC, D3-3109 commented
Please do not use Google Translate to translate English into Asian or Middle Eastern languages , this could make lots of mistakes.

2023-11-21 11:16 UTC, Zaid-maker commented
> Please do not use Google Translate to translate English into Asian or Middle Eastern languages , this could make lots of mistakes.

Yup you are correct!

2023-11-21 11:18 UTC, D3-3109 requested changes

2023-11-21 11:18 UTC, D3-3109 commented on frontend/src/lang/ar-SA.json
> +    "languageName": "الإنجليزية",
You forgot to change the language name

2023-11-21 11:18 UTC, D3-3109 commented on frontend/src/lang/hi-IN.json
> +    "languageName": "अंग्रेज़ी",
And also this one

2023-11-21 11:18 UTC, D3-3109 commented on frontend/src/lang/jp-JP.json
> +  "languageName": "英語",
and this

2023-11-21 11:18 UTC, D3-3109 commented on frontend/src/lang/ru-RU.json
> +    "languageName": "Английский",
I think Russian do not speak English

2023-11-21 15:43 UTC, louislam commented on frontend/src/lang/jp-JP.json
> +  "languageName": "英語",
Yes, it is incorrect, I think I just close this pr.

2023-11-21 15:44 UTC, closed without merging